#if DEBUG
import Foundation
import SwiftData
import SwiftUI

/// Everything the app injects at launch, with preview stand-ins: a seeded in-memory
/// store, the bundled database when it is present, a Health fake and app services
/// without a store, so nothing reconciles. `defaults` backs every `@AppStorage`.
struct PreviewEnvironment: ViewModifier {
    let container: ModelContainer
    let health: PreviewHealth
    let repository: FoodRepository
    let services: AppServices
    let defaults: UserDefaults

    func body(content: Content) -> some View {
        content
            .modelContainer(container)
            .environment(\.foodRepository, repository)
            .environment(\.health, health)
            .environment(\.healthObserving, health)
            .environment(\.appServices, services)
            .defaultAppStorage(defaults)
    }
}

extension View {
    /// Seeds a fresh container and applies the preview environment. Health is quiet by
    /// default; pass `PreviewHealth()` to see the samples other apps wrote.
    func previewEnvironment(
        seed: PreviewSeed = .typicalDay,
        health: PreviewHealth = .quiet,
        defaults: UserDefaults = PreviewDefaults.make()
    ) -> some View {
        previewEnvironment(container: PreviewStore.container(seed: seed), health: health, defaults: defaults)
    }

    /// The preview environment around a container the preview built itself, so it can
    /// fetch rows from it first.
    ///
    /// The bundled database for previews: `foods.sqlite` and `sources.json` are generated by
    /// `Tools/fooddb` and git-ignored, so they are in the bundle only after the pipeline has
    /// run on this Mac. `FoodRepository.bundled()` already answers a missing file with a
    /// repository whose database is `nil`: searches then show "Search unavailable", portion
    /// chips stay empty and the Sources screen shows the manifest error, without crashing.
    func previewEnvironment(
        container: ModelContainer,
        health: PreviewHealth = .quiet,
        defaults: UserDefaults = PreviewDefaults.make()
    ) -> some View {
        modifier(PreviewEnvironment(
            container: container,
            health: health,
            repository: FoodRepository.bundled(),
            services: AppServices(container: nil, observing: health, defaults: defaults),
            defaults: defaults
        ))
    }
}

/// `UserDefaults` suites for `@AppStorage` in previews, one per combination of flags,
/// so an onboarding preview and a main-tabs preview in the same canvas never share.
nonisolated enum PreviewDefaults {
    static func make(
        onboardingComplete: Bool = true, barcode: Bool = false,
        estimation: Bool = false, productSearch: Bool = false
    ) -> UserDefaults {
        let name = "com.j23n.omnomnom.preview.onboarding\(onboardingComplete).barcode\(barcode)"
            + ".estimation\(estimation).products\(productSearch)"
        guard let defaults = UserDefaults(suiteName: name) else { return .standard }
        defaults.set(onboardingComplete, forKey: AppServices.onboardingKey)
        defaults.set(barcode, forKey: BarcodeModule.enabledKey)
        defaults.set(estimation, forKey: EstimationModule.enabledKey)
        defaults.set(productSearch, forKey: BarcodeModule.productSearchKey)
        return defaults
    }

    /// Every opt-in switched on.
    static var modulesOn: UserDefaults {
        make(barcode: true, estimation: true, productSearch: true)
    }

    /// Fresh install: onboarding not done.
    static var onboardingPending: UserDefaults {
        make(onboardingComplete: false)
    }

    /// The three-day cadence, for the screens whose subject is which days are asked about.
    /// Its own suite, so setting it cannot leak into every other preview.
    static var threeDaysAWeek: UserDefaults {
        guard let defaults = UserDefaults(suiteName: "com.j23n.omnomnom.preview.cadence.three") else {
            return .standard
        }
        defaults.set(true, forKey: AppServices.onboardingKey)
        defaults.set(SamplingCadence.threeDaysAWeek.rawValue, forKey: SamplingCadence.key)
        return defaults
    }
}
#endif
