#if DEBUG
import Foundation

/// The bundled database for previews. `foods.sqlite` and `sources.json` are generated by
/// `Tools/fooddb` and git-ignored, so they are in the bundle only after the pipeline has
/// run on this Mac. `FoodRepository.bundled()` already answers a missing file with a
/// repository whose database is `nil`: searches then show "Search unavailable", portion
/// chips stay empty and the Sources screen shows the manifest error, without crashing.
nonisolated enum PreviewRepository {
    static func make() -> FoodRepository {
        FoodRepository.bundled()
    }

    /// A repository that behaves as if the pipeline never ran, for the missing-database states.
    static func missing() -> FoodRepository {
        FoodRepository(database: nil)
    }
}
#endif
